# Generated by Django 3.0.5 on 2023-03-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_remove_result_n_marta'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/Teacher/'),
        ),
    ]
