# Generated by Django 3.0.5 on 2023-03-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_question_question_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/Question/'),
        ),
    ]
