# Generated by Django 3.0.5 on 2023-03-08 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20230308_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_img',
        ),
    ]
